Repository Likelion-lucky7/DECO, pull requests merged in 2023-04, with the labels that each got.

#136 [회원가입 & 로그인] Light house이용 검토 Sign up login web a11y#130
  deco/index.html
  deco/src/assets/logo_big.svg
  deco/src/components/Common/FileUpload/FileUpload.jsx
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/Common/FormInput/FormInput.module.css
  deco/src/components/Common/NavBar.jsx
  deco/src/components/Common/NavBar.module.css
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/Common/SubmitButton/SubmitButton.module.css
  deco/src/components/Common/WelcomeInfo/WelcomeInfo.module.css
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/LoginPage/Login.module.css
  deco/src/components/SignUpPage/SignUp.jsx
  deco/src/components/SignUpPage/SignUp.module.css
Labels: 🎈 Accessibilty

#137 [A11y & Feat] 묻고 답하기 리스트 접근성 검토 #131, 커뮤니티 게시글 리스트 get #135
  deco/index.html
  deco/src/@store/getCommunityData.jsx
  deco/src/@store/getQuestionData.jsx
  deco/src/assets/leftPage.svg
  deco/src/assets/rightPage.svg
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/Common/Article/Article.module.css
  deco/src/components/Common/BoardBanner/BoardBanner.jsx
  deco/src/components/Common/BoardBanner/BoardBanner.module.css
  deco/src/components/Common/Category/Category.jsx
  deco/src/components/Common/Category/Category.module.css
  deco/src/components/Common/HashTag/HashTag.jsx
  deco/src/components/Common/NavBar.module.css
  deco/src/components/Common/Pagination/Pagination.jsx
  deco/src/components/Common/SearchForm/SearchForm.jsx
  deco/src/components/Common/SearchForm/SearchForm.module.css
  deco/src/components/Common/Sort/Sort.jsx
  deco/src/components/Common/Sort/Sort.module.css
  deco/src/components/CommunityPage/CommunityList.jsx
  deco/src/components/QuestionPage/QuestionCategory.jsx
  deco/src/components/QuestionPage/QuestionCategory.module.css
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/styles/theme.module.css
Labels: 🖥️ Feature, 🛠️ Refactor, 🎈 Accessibilty

#141 [Refactor] 묻고답하기 작성 페이지 접근성체크해 리팩토링
  deco/src/components/Common/FileUpload/FileUpload.jsx
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/Common/SubmitButton/SubmitButton.module.css
  deco/src/components/Common/TagInput/TagInput.module.css
  deco/src/components/Common/WriteInput/WriteInput.module.css
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.module.css
Labels: 🛠️ Refactor

#142 [Feat] 페이지네이션 기능 구현 #9
  deco/src/components/Common/Pagination/Pagination.jsx
  deco/src/components/Common/Pagination/Pagination.module.css
  deco/src/components/CommunityPage/CommunityList.jsx
  deco/src/components/QuestionPage/QuestionList.jsx
Labels: 🖥️ Feature

#144 [Refactor] 메인페이지 접근성고려 리팩토링
  deco/src/components/MainPage/ShortcutButton/ShortcutButton.module.css
  deco/src/components/MainPage/ShortcutList/ShortcutList.jsx
  deco/src/pages/MainPage.jsx
  node_modules/.package-lock.json
Labels: 🛠️ Refactor

#146 A11y after deploy#145
  deco/index.html
  deco/package-lock.json
  deco/package.json
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/Common/NavBar.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.module.css
  deco/src/components/Common/TagInput/TagInput.jsx
  deco/src/components/Common/TagInput/TagInput.module.css
  deco/src/components/Common/WriteInput/WriteInput.jsx
  deco/src/components/Common/WriteInput/WriteInput.module.css
  deco/src/components/CommunityPage/CommunityList.jsx
  deco/src/components/CommunityPage/CommunityWrite/CommunityWrite.jsx
  deco/src/components/CommunityPage/CommunityWrite/CommunityWrite.module.css
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/MainPage/ShortcutList/ShortcutList.jsx
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.module.css
  deco/src/components/SideProjectPage/SideProjectCard.jsx
  deco/src/components/SignUpPage/SignUp.jsx
  deco/src/components/SignUpPage/SignUp.module.css
  deco/src/firebase/auth/useAuthState.js
  deco/src/firebase/auth/useSignOut.js
Labels: 🐞 BugFix, 🎈 Accessibilty
