Repository Likelion-lucky7/DECO, pull requests merged in 2023-03, with the labels that each got.

#57 [Feat] 로그인 페이지 마크업 완성
  .vscode/settings.json
  deco/.eslintrc.cjs
  deco/.prettierrc.js
  deco/.prettierrc.json
  deco/index.html
  deco/package-lock.json
  deco/package.json
  deco/src/app/App.jsx
  deco/src/app/App.module.css
  deco/src/assets/DECO_Logo.svg
  deco/src/components/Common/FormInput/FormInput.jsx
  deco/src/components/Common/FormInput/FormInput.module.css
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/Common/SubmitButton/SubmitButton.module.css
  deco/src/components/Common/WelcomeInfo/WelcomeInfo.jsx
  deco/src/components/Common/WelcomeInfo/WelcomeInfo.module.css
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/LoginPage/Login.module.css
  deco/src/pages/LoginPage.jsx
  deco/src/styles/theme.module.css
  deco/vite.config.js
Labels: 🖥️ Feature

#60 [Docs] Pull Request template 생성
  .github/pull_request_template.md
Labels: 📃 Documentation

#61 [Feat] 공통 Header 마크업 완료
  deco/src/components/Common/NavBar.jsx
  deco/src/components/Common/NavBar.module.css
  deco/src/styles/reset.module.css
  deco/src/styles/theme.module.css
Labels: 🖥️ Feature

#67 [Feat] 사이드 프로젝트 게시글 작성 페이지 머지 요청#58
  deco/.eslintrc.cjs
  deco/.gitignore
  deco/src/app/App.jsx
  deco/src/assets/sideproject/calendar_icon.png
  deco/src/assets/sideproject/check.png
  deco/src/assets/sideproject/down_arrow_icon.png
  deco/src/assets/sideproject/nonecheck.png
  deco/src/assets/sideproject/uploadButton.png
  deco/src/assets/sideproject/등록버튼.png
  deco/src/components/SideProjectPage/SideProjectWrite.jsx
  deco/src/components/SideProjectPage/SideProjectWrite.module.css
Labels: 🖥️ Feature

#69 Question detail#52
  deco/src/app/App.jsx
  deco/src/app/App.module.css
  deco/src/assets/dots_three_icon.png
  deco/src/assets/empty_picture.png
  deco/src/assets/likeActivate.png
  deco/src/assets/likeDisable.png
  deco/src/components/QuestionPage/AnswerEditor/AnswerEditor.jsx
  deco/src/components/QuestionPage/AnswerEditor/AnswerEditor.module.css
  deco/src/components/QuestionPage/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/QuestionPage/QuestionAnswer/QuestionAnswer.module.css
  deco/src/components/QuestionPage/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
  deco/src/components/QuestionPage/QuestionDetail/QuestionLogOut.jsx
Labels: 🖥️ Feature

#70 [Feat] 묻고 답하기, 커뮤니티 글 작성 페이지 마크업 #66
  deco/src/assets/DECO_Logo.svg
  deco/src/assets/login/file_upload.svg
  deco/src/assets/login/logo_big.svg
  deco/src/assets/login/profile.svg
  deco/src/components/Common/FileUpload/FileUpload.jsx
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/Common/SubmitButton/SubmitButton.module.css
  deco/src/components/Common/TagInput/TagInput.jsx
  deco/src/components/Common/TagInput/TagInput.module.css
  deco/src/components/Common/WriteInput/WriteInput.jsx
  deco/src/components/Common/WriteInput/WriteInput.module.css
  deco/src/components/CommunityPage/CommunityWrite.jsx
  deco/src/components/CommunityPage/CommunityWrite/CommunityWrite.jsx
  deco/src/components/CommunityPage/CommunityWrite/CommunityWrite.module.css
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/LoginPage/Login.module.css
  deco/src/components/QuestionPage/QuestionWrite.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.module.css
  deco/src/components/SignUpPage/SignUp.jsx
  deco/src/components/SignUpPage/SignUp.module.css
Labels: 🖥️ Feature

#71 Common board list#25
  deco/package-lock.json
  deco/package.json
  deco/src/app/App.module.css
  deco/src/assets/leftPage.svg
  deco/src/assets/loveIcon.svg
  deco/src/assets/rightPage.svg
  deco/src/assets/searchIcon.svg
  deco/src/assets/writeIcon.svg
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/Common/Article/Article.module.css
  deco/src/components/Common/BoardBanner/BoardBanner.jsx
  deco/src/components/Common/BoardBanner/BoardBanner.module.css
  deco/src/components/Common/Category/Category.jsx
  deco/src/components/Common/Category/Category.module.css
  deco/src/components/Common/HashTag/HashTag.jsx
  deco/src/components/Common/HashTag/HashTag.module.css
  deco/src/components/Common/Pagination/Pagination.jsx
  deco/src/components/Common/Pagination/Pagination.module.css
  deco/src/components/Common/SearchForm/SearchForm.jsx
  deco/src/components/Common/SearchForm/SearchForm.module.css
  deco/src/components/Common/Sort/Sort.jsx
  deco/src/components/Common/Sort/Sort.module.css
  deco/src/components/CommunityPage/CommunityList.jsx
  deco/src/components/CommunityPage/CommunityList.module.css
  deco/src/components/QuestionPage/QuestionCategory.jsx
  deco/src/components/QuestionPage/QuestionCategory.module.css
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/components/QuestionPage/QuestionList.module.css
  deco/src/components/SideProjectPage/SideProjectCard.module.css
  deco/src/components/SideProjectPage/SideProjectList.jsx
  deco/src/components/SideProjectPage/SideProjectList.module.css
  deco/src/styles/index.css
  node_modules/.package-lock.json
Labels: 🖥️ Feature

#72 Common board list#25-Sort css 수정, .env삭제
  deco/.env
  deco/src/app/App.jsx
  deco/src/components/Common/Sort/Sort.module.css
  deco/src/styles/reset.module.css
Labels: 🌈 Style

#73 [Feat} 사이드 프로젝트페이지 상세페이지 및 리팩토링 후 머지 요청 #59
  db.json
  deco/src/app/App.jsx
  deco/src/assets/like_activate.svg
  deco/src/assets/sideproject/like.svg
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/SideProjectPage/SideProjectCard.jsx
  deco/src/components/SideProjectPage/SideProjectCard.module.css
  deco/src/components/SideProjectPage/SideProjectDetail.jsx
  deco/src/components/SideProjectPage/SideProjectDetail.module.css
  deco/src/components/SideProjectPage/SideProjectList.jsx
  deco/src/components/SideProjectPage/Tag.jsx
  deco/src/components/SideProjectPage/Tag.module.css
  deco/src/components/SideProjectPage/sideProjectWrite/SideProjectWrite.jsx
  deco/src/components/SideProjectPage/sideProjectWrite/SideProjectWrite.module.css
Labels: 🖥️ Feature

#74 [Rename] 상세페이지 className 재지정 하고 이미지였던 좋아요버튼을 버튼으로 바꿨습니다.
  deco/src/assets/likeActivate.png
  deco/src/assets/likeActivate.svg
  deco/src/components/QuestionPage/AnswerEditor/AnswerEditor.jsx
  deco/src/components/QuestionPage/AnswerEditor/AnswerEditor.module.css
  deco/src/components/QuestionPage/QuestionAnswer/QuestionAnswer.module.css
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
Labels: 🌈 Style

#78 [Style] 묻고 답하기 상세 페이지 디자인 수정
  deco/src/assets/heartActivate.svg
  deco/src/assets/likeDisable.png
  deco/src/components/Common/AnswerEditor/AnswerEditor.jsx
  deco/src/components/Common/AnswerEditor/AnswerEditor.module.css
  deco/src/components/Common/Comment/Comment.jsx
  deco/src/components/Common/Comment/Comment.module.css
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
Labels: 🌈 Style

#79 Question detail get#14
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
Labels: 🖥️ Feature

#80 목업데이터를 이용한 묻고 답하기 글 목록 get - Question list get#75
  deco/.gitignore
  deco/src/app/App.jsx
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/Common/Article/Article.module.css
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/components/SideProjectPage/SideProjectList.jsx
Labels: 🖥️ Feature

#83 [Feat] 묻고 답하기 상세 페이지 댓글 post 기능 구현 #27
  deco/src/@store/commentState.js
  deco/src/app/App.jsx
  deco/src/components/Common/AnswerEditor/AnswerEditor.jsx
  deco/src/components/Common/AnswerEditor/AnswerEditor.module.css
  deco/src/components/Common/Comment/Comment.jsx
  deco/src/components/Common/Comment/Comment.module.css
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.module.css
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
  deco/src/firebase/app.js
  deco/src/firebase/firestore/index.js
  deco/src/firebase/firestore/useCreateData.js
  deco/src/main.jsx
Labels: 🖥️ Feature

#88 [Feat] 댓글 ⋯ 버튼 컴포넌트 구현 #86
  deco/src/components/Common/AnswerEditor/AnswerEditor.jsx
  deco/src/components/Common/AnswerEditor/AnswerEditor.module.css
  deco/src/components/Common/DotButton/DotButton.jsx
  deco/src/components/Common/DotButton/DotButton.module.css
Labels: 🖥️ Feature

#89 [Feat] 묻고 답하기 작성란 POST 요청 #30
  deco/db.json
  deco/package-lock.json
  deco/package.json
  deco/src/@store/contentState.js
  deco/src/@store/hashTagState.js
  deco/src/@store/titleState.js
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/Common/TagInput/TagInput.jsx
  deco/src/components/Common/WriteInput/WriteInput.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
  deco/src/firebase/firestore/useCreateData.js
Labels: 🖥️ Feature

#92 [묻고답하기] 상세페이지에서 수정기능 #22
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/firebase/firestore/useCreateData.js
Labels: 🖥️ Feature

#93 Firebase Auth를 이용한 회원가입 로그인 연결 - Sign up and login#43
  deco/.gitignore
  deco/db.json
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/SignUpPage/SignUp.jsx
  deco/src/firebase/app.js
  deco/src/firebase/auth.js
  deco/src/firebase/database.js
Labels: 🖥️ Feature

#97 [Feat] 묻고 답하기 리스트 조회 파이어베이스로 변경 #95
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/firebase/app.js
Labels: 🛠️ Refactor

#98 [Feat] 묻고 답하기 작성란 해시태그 구현 #91
  deco/src/@store/hashTagListState.js
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/components/Common/TagInput/TagInput.jsx
  deco/src/components/Common/TagInput/TagInput.module.css
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
  deco/src/firebase/firestore/useCreateData.js
Labels: 🖥️ Feature

#101 [Feat] 댓글 수정, 삭제 기능 구현 #31
  deco/src/@store/commentUpdateState.js
  deco/src/components/Common/AnswerEditor/AnswerEditor.jsx
  deco/src/components/Common/AnswerEditor/AnswerEditor.module.css
  deco/src/components/Common/Comment/Comment.jsx
  deco/src/components/Common/DotButton/DotButton.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.module.css
  deco/src/components/Common/SubmitButton/SubmitButton.jsx
  deco/src/firebase/firestore/index.js
  deco/src/firebase/firestore/useDeleteData.js
  deco/src/firebase/firestore/useUpdateData.js
Labels: 🖥️ Feature

#103 묻고답하기 리스트 및 게시글 상세조회시 리코일 적용 #81
  deco/src/@store/getQuestionData.jsx
  deco/src/app/App.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionList.jsx
Labels: 🖥️ Feature

#105 파이어베이스 이용해서 댓글 정렬과 글 id로 분류
  deco/src/components/Common/AnswerEditor/AnswerEditor.module.css
  deco/src/components/Common/Comment/Comment.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
Labels: 🖥️ Feature

#108 [Feat] 이미지 업로드시 미리보기 및 firebase storage에 저장 #99
  deco/src/@store/fileImageState.js
  deco/src/components/Common/FileUpload/FileUpload.jsx
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
  deco/src/firebase/storage/index.js
  deco/src/firebase/storage/useUploadFile.js
Labels: 🖥️ Feature

#110 [Feat] 회원가입에서 닉네임과 프로필사진까지 받기 Sign up update profile#45
  deco/src/@store/authUserState.js
  deco/src/components/Common/FileUpload/FileUpload.jsx
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/LoginPage/Login.module.css
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/components/SignUpPage/SignUp.jsx
  deco/src/components/SignUpPage/SignUp.module.css
  deco/src/firebase/app.js
  deco/src/firebase/auth.js
  deco/src/firebase/auth/index.js
  deco/src/firebase/auth/useAuthState.js
  deco/src/firebase/auth/useSignIn.js
  deco/src/firebase/auth/useSignOut.js
  deco/src/firebase/auth/useSignUp.js
  deco/src/firebase/firestore/index.js
  deco/src/firebase/firestore/useCreateAuthUser.js
  deco/src/firebase/storage/README.md
  deco/src/firebase/storage/index.js
  deco/src/firebase/storage/useDeleteFile.js
  deco/src/firebase/storage/useDownloadURL.js
  deco/src/firebase/storage/useUploadFile.js
  deco/src/pages/MainPage.jsx
Labels: 🖥️ Feature

#111 묻고 답하기 상세페이지 수정 및 삭제 구현완료#15
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.module.css
Labels: 🖥️ Feature

#115 [Feat] 회원가입 조건 충족 여부에 따른 안내 띄워주기
  deco/src/@store/authUserState.js
  deco/src/components/Common/NavBar.jsx
  deco/src/components/Common/NavBar.module.css
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/SignUpPage/SignUp.jsx
  deco/src/components/SignUpPage/SignUp.module.css
Labels: 🖥️ Feature

#116 [Feat] 묻고 답하기 작성란 카테고리 및 상세페이지 Navigate 구현 #109
  deco/src/@store/selectState.js
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/Common/FileUpload/FileUpload.module.css
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.module.css
  deco/src/firebase/firestore/useReadData.js
Labels: 🖥️ Feature

#119 [Feat]로그인 로그아웃시 전역상태관리#117
  deco/src/@store/getQuestionData.jsx
  deco/src/@store/user.js
  deco/src/components/Common/Article/Article.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
  deco/src/components/QuestionPage/QuestionList.jsx
  deco/src/firebase/auth/useSignIn.js
  deco/src/firebase/auth/useSignOut.js
  node_modules/.package-lock.json
Labels: 🖥️ Feature

#120 [Feat] 로그인 성공 시 직전 페이지로 이동 #48
  deco/src/components/Common/NavBar.jsx
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/SignUpPage/SignUp.jsx
Labels: 🖥️ Feature

#121 커뮤니티 페이지 article 컴포넌트 주석처리 & 댓글 버그 수정
  deco/src/@store/getCommunityData.jsx
  deco/src/components/Common/Comment/Comment.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
  deco/src/components/CommunityPage/CommunityDetail.jsx
  deco/src/components/CommunityPage/CommunityDetail.module.css
  deco/src/components/CommunityPage/CommunityList.jsx
Labels: 🖥️ Feature

#122 [Feat] 묻고 답하기 작성란 전반적인 데이터 POST #118
  deco/package-lock.json
  deco/package.json
  deco/src/components/Common/WriteInput/WriteInput.jsx
  deco/src/components/QuestionPage/QuestionWrite/QuestionWrite.jsx
Labels: 🖥️ Feature

#125 [Add] 댓글 로그인 정보에 따라 이미지와 닉네임 불러오기
  deco/src/components/Common/AnswerEditor/AnswerEditor.jsx
  deco/src/components/Common/Comment/Comment.jsx
  deco/src/components/Common/QuestionAnswer/QuestionAnswer.jsx
Labels: 🛠️ Refactor

#127 [Bug] 댓글에서 유저 인증상태에 따른 수정, 삭제 버튼 활성화 Delete modify#126
  deco/src/components/Common/AnswerEditor/AnswerEditor.jsx
  deco/src/components/LoginPage/Login.jsx
  deco/src/components/QuestionPage/QuestionDetail/QuestionDetail.jsx
Labels: 🐞 BugFix
